#.travis.yml

sudo: required
addons:
  chrome: stable

language: node_js

node_js:
  - 8

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
- npm set progress=false
- npm install

script:
- ng lint
- npm run test